#: Normalized versions of state names
STATES_NORMALIZED = {
    "ak": "AK",
    "al": "AL",
    "ala": "AL",
    "alabama": "AL",
    "alaska": "AK",
    "ar": "AR",
    "ariz": "AZ",
    "arizona": "AZ",
    "ark": "AR",
    "arkansas": "AR",
    "az": "AZ",
    "ca": "CA",
    "calf": "CA",
    "calif": "CA",
    "california": "CA",
    "co": "CO",
    "colo": "CO",
    "colorado": "CO",
    "conn": "CT",
    "connecticut": "CT",
    "ct": "CT",
    "dc": "DC",
    "de": "DE",
    "del": "DE",
    "delaware": "DE",
    "deleware": "DE",
    "district of columbia": "DC",
    "fl": "FL",
    "fla": "FL",
    "florida": "FL",
    "ga": "GA",
    "georgia": "GA",
    "hawaii": "HI",
    "hi": "HI",
    "ia": "IA",
    "id": "ID",
    "idaho": "ID",
    "il": "IL",
    "ill": "IL",
    "illinois": "IL",
    "in": "IN",
    "ind": "IN",
    "indiana": "IN",
    "iowa": "IA",
    "kan": "KS",
    "kans": "KS",
    "kansas": "KS",
    "kentucky": "KY",
    "ks": "KS",
    "ky": "KY",
    "la": "LA",
    "louisiana": "LA",
    "ma": "MA",
    "maine": "ME",
    "maryland": "MD",
    "mass": "MA",
    "massachusetts": "MA",
    "massachussetts": "MA",
    "md": "MD",
    "me": "ME",
    "mi": "MI",
    "mich": "MI",
    "michigan": "MI",
    "minn": "MN",
    "minnesota": "MN",
    "miss": "MS",
    "mississippi": "MS",
    "missouri": "MO",
    "mn": "MN",
    "mo": "MO",
    "mont": "MT",
    "montana": "MT",
    "n d": "ND",
    "n dak": "ND",
    "n h": "NH",
    "n j": "NJ",
    "n m": "NM",
    "n mex": "NM",
    "nc": "NC",
    "nd": "ND",
    "ne": "NE",
    "neb": "NE",
    "nebr": "NE",
    "nebraska": "NE",
    "nev": "NV",
    "nevada": "NV",
    "new hampshire": "NH",
    "new jersey": "NJ",
    "new mexico": "NM",
    "new york": "NY",
    "nh": "NH",
    "nj": "NJ",
    "nm": "NM",
    "nmex": "NM",
    "north carolina": "NC",
    "north dakota": "ND",
    "nv": "NV",
    "ny": "NY",
    "oh": "OH",
    "ohio": "OH",
    "ok": "OK",
    "okla": "OK",
    "oklahoma": "OK",
    "or": "OR",
    "ore": "OR",
    "oreg": "OR",
    "oregon": "OR",
    "pa": "PA",
    "penn": "PA",
    "pennsylvania": "PA",
    "rhode island": "RI",
    "ri": "RI",
    "s dak": "SD",
    "sc": "SC",
    "sd": "SD",
    "sdak": "SD",
    "south carolina": "SC",
    "south dakota": "SD",
    "tenn": "TN",
    "tennessee": "TN",
    "territory of hawaii": "HI",
    "tex": "TX",
    "texas": "TX",
    "tn": "TN",
    "tx": "TX",
    "ut": "UT",
    "utah": "UT",
    "va": "VA",
    "vermont": "VT",
    "viginia": "VA",
    "virgina": "VA",
    "virginia": "VA",
    "vt": "VT",
    "w va": "WV",
    "wa": "WA",
    "wash": "WA",
    "washington": "WA",
    "west virginia": "WV",
    "wi": "WI",
    "wis": "WI",
    "wisc": "WI",
    "wisconsin": "WI",
    "wv": "WV",
    "wva": "WV",
    "wy": "WY",
    "wyo": "WY",
    "wyoming": "WY",
}
